version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - ls -al
      - pwd
      - export BUCKET=test-lambda-ath-pl-bucket
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml